// app/src/components/table/actions/search-box.jsx
/* global wp */
import React, { useState } from 'react'
import { useInstanceId } from '@wordpress/compose'

const { __ } = wp.i18n

/**
 * Search input component for the listing table header.
 *
 * @since 4.0.0
 *
 * @param {*} param0
 * @returns {*}
 */
const SearchBox = ({ onSearch }) => {
	const id = useInstanceId(SearchBox)
	const [search, setSearch] = useState('')

	return (
		<p className="search-box">
			<label
				className="screen-reader-text"
				htmlFor={`search-input-${id}`}
			>
				{__('Search:', '404-to-301')}
			</label>
			<input
				type="search"
				id={`search-input-${id}`}
				name={`search-input-${id}`}
				value={search}
				onChange={(ev) => setSearch(ev.target.value)}
			/>
			<button
				type="button"
				className="button"
				onClick={() => onSearch(search)}
			>
				{__('Search', '404-to-301')}
			</button>
		</p>
	)
}

export default SearchBox

// app/src/components/list-table/search-box.vue
<template>
    <p class="search-box">
        <label class="screen-reader-text"
               :for="id"
        >
            {{ label || $i18n.labels.search }}:
        </label>

        <input type="search"
               :id="id"
               v-model="search"
               @change="handleInput"
        />
        <button type="button"
                class="button"
                @click="doSearch"
        >
            {{ label }}
        </button>
    </p>
</template>

<script>

	export default {
		name: 'SearchBox',

		props: {
			id: {
				type: String,
				required: true
			},
			label: {
				type: String,
			},
			value: {
				type: String,
			}
		},

		data() {
			return {
				search: this.value,
			}
		},

		methods: {
			doSearch() {
				this.$emit( 'submitSearch', this.id );
			},

			handleInput() {
				this.$emit( 'input', this.search );
			}
		}
	};
</script>
