// app/src/scripts/modules/settings/tabs/tab-info.vue
<template>
	<h4><span class="dashicons dashicons-sos"></span> Help & Support</h4>
	<p>We are fanatical about support, and want you to get the best out of your website with 404 to 301. If you run into any difficulties, there are several places you can find help:</p>
	<ul class="duckdev-list-dots">
		<li>
			<p>
				📚&nbsp;&nbsp;<a href="https://duckdev.com/docs/404-to-301/" target="_blank">Documentation</a> -
				Our extensive documentation contains references and guides for most situations you may encounter.
			</p>
		</li>
		<li>
			<p>
				🫂&nbsp;&nbsp;<a href="https://wordpress.org/support/plugin/404-to-301/" target="_blank">Support Forums</a> -
				We have an active and friendly community on our wp.org forum who may be able to help you figure out the ‘how-tos’ of the 404 to 301 world.
			</p>
		</li>
		<li>
			<p>
				📧&nbsp;&nbsp;<a href="https://duckdev.com/contact/" target="_blank">Contact Author</a> -
				If the above options did not help you can reach out to me directly through my contact form. Please note, it may take a few days for me to reply as I am the only developer working on new features, bug fixes, improvements, documentation, customer support etc. after my full time job.
			</p>
		</li>
	</ul>

	<hr/>

	<h4><span class="dashicons dashicons-admin-plugins"></span> Other Plugins</h4>
	<p>Hey, I am Joel James, a WordPress developer from Kerala, India. I spend a few hours every week to contribute to open source. I have a few other WordPress plugin which I would recommend you to try out.</p>
	<ul class="duckdev-list-dots">
		<li>
			<p>
				🦥&nbsp;&nbsp;<a href="https://wordpress.org/plugins/lazy-load-for-comments/" target="_blank">Lazy Load for Comments</a>
			</p>
		</li>
		<li>
			<p>
				🔐&nbsp;&nbsp;<a href="https://wordpress.org/plugins/loggedin/" target="_blank">Loggedin - Limit Active Logins</a>
			</p>
		</li>
		<li>
			<p>
				and <a href="https://profiles.wordpress.org/joelcj91/#content-plugins" target="_blank">a few more...</a>
			</p>
		</li>
	</ul>
</template>

<script>
export default {
	name: 'TabInfo',

	props: {},

	data() {
		return {}
	},

	methods: {}
}
</script>

// app/src/scripts/settings/tab-info.jsx
const {Component} = wp.element
const {__} = wp.i18n
const {
	Button,
	PanelBody
} = wp.components

export default class TabInfo extends Component {
	constructor(props) {
		super(props);
		this.state = {}
	}

	render() {
		return (
			<PanelBody title={__('Help & Support', '404-to-301')}>
				<div className="dd4t3-info">
					<p>{__('Our extensive documentation contains references and guides for most situations you may encounter. We have an active and friendly community on our wp.org forum who may be able to help you figure out the ‘how-tos’ of the 404 to 301 world.', '404-to-301')}</p>
					<p>{__('If the above options did not help you can reach out to me directly through my contact form. Please note, it may take a few days for me to reply as I am the only developer working on new features, bug fixes, improvements, documentation, customer support etc. after my full time job.', '404-to-301')}</p>
					<div className="dd4t3-info-button-group">
						<Button
							variant="secondary"
							target="_blank"
							icon="external"
							href="https://duckdev.com/docs/404-to-301/"
						>
							{__('Documentation', '404-to-301')}
						</Button>

						<Button
							variant="secondary"
							target="_blank"
							icon="external"
							href="https://wordpress.org/support/plugin/404-to-301/"
						>
							{__('Support Forums', '404-to-301')}
						</Button>
					</div>
				</div>
			</PanelBody>
		);
	}
}
